POST http://172.20.10.13:8000/custom_auth/login
Content-Type: application/json

{
    "username": "katherine",
    "password": "kkliu"
}

###

POST http://172.20.10.13:8000/custom_auth/signup
Content-Type: application/json

{
    "username": "Red_Cross",
    "password": "Red Cross",
    "email": "john@gmail.com",
    "is_admin": false,
    "is_charity": true,
    "wallet_addr": "0x123",
    "text_desc": "The Red Cross is a renowned humanitarian organization dedicated to providing emergency assistance, disaster relief, and education in regions affected by crises.",
    "subtitle": "Medical Emergencies"

}

###

GET http://10.49.128.64:8000/custom_auth/test_token
Content-Type: application/json
Authorization: Token af086b07fcaddeff6fda17b41c0f1f3caec189d7

###
GET http://172.20.10.13:8000/charity_info/get_causes
Content-Type: application/json

{
    "charity_name": "GoFundMe"
}

###
GET http://172.20.10.13:8000/charity_info/get_transactions
Content-Type: application/json

{
    "username": "katherine"
}

###
POST http://172.20.10.13:8000/charity_info/post_transactions
Content-Type: application/json

{
    "username": "katherine",
    "charity_name": "GaysForGaza",
    "amount": 103330.1
}
###
GET http://172.20.10.13:8000/charity_info/get_charity_total
Content-Type: application/json

{
    "charity_name": "GaysForGaza"
}

###
GET http://172.20.10.13:8000/charity_info/get_charity_transactions
Content-Type: application/json

{
    "charity_name": "GoFundMe"
}

###
POST http://172.20.10.13:8000/charity_info/add_cause
Content-Type: application/json

{
    "is_approved": true,
    "cause_name": "Chelsea's chicken's surgery",
    "charity_name": "GoFundMe",
    "wallet_addr": "0x1ibpu3ewwrci3231pu23ee233",
    "cause_desc": "We are raising money to keep Chelsea's chicken alive"
}

###
POST http://172.20.10.13:8000/charity_info/post_charity_transactions
Content-Type: application/json

{
    "charity_name": "GoFundMe",
    "cause_name": "Johnny's Fish Surgery",
    "amount": 0.1000
}

###
GET http://172.20.10.13:8000/charity_info/get_all_charities
Content-Type: application/json

{
}