# Generated by Django 4.2.13 on 2024-05-19 03:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='charity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='causes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cause',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charity_transaction',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user_transaction',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
