# Generated by Django 4.2.13 on 2024-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_account_subtitle_account_text_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='img_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
