# Generated by Django 4.2.13 on 2024-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_account_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
